In [51]:
import pandas as pd
import numpy as np

java = pd.read_csv('../java_mb_KG.txt',names=['user','item','behavior','time'], sep='\t')
java

user  item  behavior        time
0        1   305     watch  1406863244
1        1   172      done  1410874261
2        1    54      done  1410874265
3        1    54  duration  1410874275
4        1   314      done  1410913417
...    ...   ...       ...         ...
2489   183   294      done  1429083169
2490   183   294       tag  1429083255
2491   183   294  duration  1429083393
2492   183   357      done  1429084813
2493   183   357  duration  1429085601

[2494 rows x 4 columns]

In [91]:
class user:
    def __init__(self, user_id) -> None:
        self.sequence = []
        self.behavior = []
        self.timestamp = []
        self.user = user_id
    
    def get_seq_len(self):
        return len(self.sequence)

    def get_seq_part(self,i):
        self.length = self.get_seq_len()
        if i>self.length:
            return self.sequence
        else:
            return self.sequence[:i]

    def add_seq(self,data):
        self.sequence.append(data['item'])
        self.behavior.append(data['behavior'])
        self.timestamp.append(data['time'])

    def find(self,x):
        if x in self.sequence:
            t = self.sequence.index(x)
            return t+1
        else:
            return -1

    def set_user(self, user_id, seq, beh, t):
        self.user = user_id
        self.sequence = seq
        self.behavior = beh
        self.timestamp = t

u = []
for i in range(184):
    tmp = user(i)
    u.append(tmp)

temp = 0
for index, row in java.iterrows():
    u[row['user']].add_seq(row)



In [75]:
len(u)

184

In [76]:
u[1].get_seq_len()

76

In [92]:
res = []
for i in range(184):
    res.append(u[i].sequence)

In [93]:
length = []
for s in res:
    length.append(len(s))
print(min(length),np.average(length),max(length))

0 13.554347826086957 132


In [94]:
java2 = java.to_numpy()
java2

array([[1, 305, 'watch', 1406863244],
       [1, 172, 'done', 1410874261],
       [1, 54, 'done', 1410874265],
       ...,
       [183, 294, 'duration', 1429083393],
       [183, 357, 'done', 1429084813],
       [183, 357, 'duration', 1429085601]], dtype=object)

In [95]:
import random

enhance = []
u2_list = []
i=184
for _ in range(50):
    t1 = random.randint(1,183)
    t2 = random.randint(1,183)
    u1 = u[t1]
    #print(u1.user, u1.get_seq_len())
    u2 = u[t2]
    u1_len = u1.get_seq_len()
    k1 = random.randint(1,u1_len-1)
    x = u1.sequence[k1]
    flag = u2.find(x)
    #print(flag)
    flag_time = u1.timestamp[k1]
    if flag>0:
        new = u1.sequence[:k1]+u2.sequence[flag:]
        beh = u1.behavior[:k1]+u2.behavior[flag:]
        tt = [xx + abs(flag_time - u2.timestamp[flag]) for xx in u2.timestamp[flag:]]
        t = u1.timestamp[:k1]+tt
        if len(new)>3:
            us = user(i)
            us.set_user(i, new, beh, t)
            enhance.append(new)
            u2_list.append(us)
            i+=1

for x in enhance:
    print(len(x))

6
6
12
10
5
6
5
7
7
4
17
20
11
8
13
14
5
5
4
5
5
4
4
5


In [96]:
# 以上为随机拼接
new_res = []
def gen_new(u):
    length = u.get_seq_len()
    for i in range(length):
        tmp = [u.user, u.sequence[i], u.behavior[i], u.timestamp[i]]
        new_res.append(tmp)
for u_i in u2_list:
    gen_new(u_i)

new_res = np.array(new_res)

In [98]:
new_java = np.concatenate((java2, new_res), axis=0)
new_java

array([[1, 305, 'watch', 1406863244],
       [1, 172, 'done', 1410874261],
       [1, 54, 'done', 1410874265],
       ...,
       ['207', '363', 'done', '1416467318'],
       ['207', '301', 'done', '1434998988'],
       ['207', '301', 'duration', '1435000153']], dtype=object)

In [99]:
new_java2 = pd.DataFrame(new_java)
new_java2

0    1         2           3
0       1  305     watch  1406863244
1       1  172      done  1410874261
2       1   54      done  1410874265
3       1   54  duration  1410874275
4       1  314      done  1410913417
...   ...  ...       ...         ...
2677  207    1       tag  1416276708
2678  207  363     enter  1416467310
2679  207  363      done  1416467318
2680  207  301      done  1434998988
2681  207  301  duration  1435000153

[2682 rows x 4 columns]

In [100]:
new_java2.to_csv('java_mb_KG_e1.txt', sep = '\t', index=False, header=None)

In [1]:
import pandas as pd
import numpy as np

os = pd.read_csv('../os_mb_KG.txt',names=['user','item','behavior','time'], sep='\t')
os

user  item  behavior        time
0        1   397       tag  1429497734
1        1   428      done  1429497741
2        1   429      done  1429497796
3        1   417      done  1429497920
4        1   428       tag  1429499516
...    ...   ...       ...         ...
4695   304   476  duration  1428396833
4696   305   397       tag  1428674222
4697   305   398      done  1428674265
4698   305   398  duration  1428677285
4699   305   398       tag  1428677286

[4700 rows x 4 columns]

In [2]:
class user:
    def __init__(self, user_id) -> None:
        self.sequence = []
        self.behavior = []
        self.timestamp = []
        self.user = user_id
    
    def get_seq_len(self):
        return len(self.sequence)

    def get_seq_part(self,i):
        self.length = self.get_seq_len()
        if i>self.length:
            return self.sequence
        else:
            return self.sequence[:i]

    def add_seq(self,data):
        self.sequence.append(data['item'])
        self.behavior.append(data['behavior'])
        self.timestamp.append(data['time'])

    def find(self,x):
        if x in self.sequence:
            t = self.sequence.index(x)
            return t+1
        else:
            return -1

    def set_user(self, user_id, seq, beh, t):
        self.user = user_id
        self.sequence = seq
        self.behavior = beh
        self.timestamp = t

In [3]:
u_os = []
for i in range(306):
    tmp = user(i)
    u_os.append(tmp)

temp = 0
for index, row in os.iterrows():
    u_os[row['user']].add_seq(row)

In [4]:
len(u_os)

306

In [5]:
u_os[1].get_seq_len()

10

In [6]:
res_os = []
for i in range(306):
    res_os.append(u_os[i].sequence)

In [7]:
length_os = []
for s in res_os:
    length_os.append(len(s))
print(min(length_os),np.average(length_os),max(length_os))

0 15.359477124183007 199


In [8]:
os2 = os.to_numpy()
os2

array([[1, 397, 'tag', 1429497734],
       [1, 428, 'done', 1429497741],
       [1, 429, 'done', 1429497796],
       ...,
       [305, 398, 'done', 1428674265],
       [305, 398, 'duration', 1428677285],
       [305, 398, 'tag', 1428677286]], dtype=object)

In [9]:
import random

enhance_os = []
u2_list_os = []
i=306
for _ in range(50):
    t1 = random.randint(1,305)
    t2 = random.randint(1,305)
    u1 = u_os[t1]
    #print(u1.user, u1.get_seq_len())
    u2 = u_os[t2]
    u1_len = u1.get_seq_len()
    k1 = random.randint(1,u1_len-1)
    x = u1.sequence[k1]
    flag = u2.find(x)
    #print(flag)
    flag_time = u1.timestamp[k1]
    if flag>0:
        new = u1.sequence[:k1]+u2.sequence[flag:]
        beh = u1.behavior[:k1]+u2.behavior[flag:]
        tt = [xx + abs(flag_time - u2.timestamp[flag]) for xx in u2.timestamp[flag:]]
        t = u1.timestamp[:k1]+tt
        if len(new)>3:
            us = user(i)
            us.set_user(i, new, beh, t)
            enhance_os.append(new)
            u2_list_os.append(us)
            i+=1

for x in enhance_os:
    print(len(x))

60
4
9
47
17
4
34
18
30
6
7
5
9
22
6
16
8
12
10
20
5
46
11


In [10]:
# 以上为随机拼接
new_res_os = []
def gen_new(u):
    length = u.get_seq_len()
    for i in range(length):
        tmp = [u.user, u.sequence[i], u.behavior[i], u.timestamp[i]]
        new_res_os.append(tmp)
for u_i in u2_list_os:
    gen_new(u_i)

new_res_os = np.array(new_res_os)

In [11]:
new_os = np.concatenate((os2, new_res_os), axis=0)
new_os

array([[1, 397, 'tag', 1429497734],
       [1, 428, 'done', 1429497741],
       [1, 429, 'done', 1429497796],
       ...,
       ['328', '397', 'done', '1429717354'],
       ['328', '397', 'tag', '1436223106'],
       ['328', '397', 'watch', '1436223943']], dtype=object)

In [12]:
new_os2 = pd.DataFrame(new_os)
new_os2

0    1      2           3
0       1  397    tag  1429497734
1       1  428   done  1429497741
2       1  429   done  1429497796
3       1  417   done  1429497920
4       1  428    tag  1429499516
...   ...  ...    ...         ...
5101  328    6   done  1429715608
5102  328  397  enter  1429717194
5103  328  397   done  1429717354
5104  328  397    tag  1436223106
5105  328  397  watch  1436223943

[5106 rows x 4 columns]

In [13]:
new_os2.to_csv('os_mb_KG_e1.txt', sep = '\t', index=False, header=None)

In [14]:
import pandas as pd
import numpy as np

net = pd.read_csv('../net_mb_KG.txt',names=['user','item','behavior','time'], sep='\t')
net

user  item behavior        time
0        1     1    enter  1413883798
1        1     1     done  1413883869
2        1     1    watch  1415244162
3        1     1      tag  1415330742
4        2     1    watch  1414155169
...    ...   ...      ...         ...
3591   246   285     done  1429539992
3592   246   286     done  1429624580
3593   246   287      tag  1429753275
3594   246     1      tag  1429794648
3595   246   287     done  1429794803

[3596 rows x 4 columns]

In [16]:
u_net = []
for i in range(247):
    tmp = user(i)
    u_net.append(tmp)

temp = 0
for index, row in net.iterrows():
    u_net[row['user']].add_seq(row)

In [17]:
len(u_net)

247

In [18]:
u_net[1].get_seq_len()

4

In [20]:
res_net = []
for i in range(247):
    res_net.append(u_net[i].sequence)

In [21]:
length_net = []
for s in res_net:
    length_net.append(len(s))
print(min(length_net),np.average(length_net),max(length_net))

0 14.558704453441296 122


In [22]:
net2 = net.to_numpy()
net2

array([[1, 1, 'enter', 1413883798],
       [1, 1, 'done', 1413883869],
       [1, 1, 'watch', 1415244162],
       ...,
       [246, 287, 'tag', 1429753275],
       [246, 1, 'tag', 1429794648],
       [246, 287, 'done', 1429794803]], dtype=object)

In [23]:
import random

enhance_net = []
u2_list_net = []
i=247
for _ in range(50):
    t1 = random.randint(1,246)
    t2 = random.randint(1,246)
    u1 = u_net[t1]
    #print(u1.user, u1.get_seq_len())
    u2 = u_net[t2]
    u1_len = u1.get_seq_len()
    k1 = random.randint(1,u1_len-1)
    x = u1.sequence[k1]
    flag = u2.find(x)
    #print(flag)
    flag_time = u1.timestamp[k1]
    if flag>0:
        new = u1.sequence[:k1]+u2.sequence[flag:]
        beh = u1.behavior[:k1]+u2.behavior[flag:]
        tt = [xx + abs(flag_time - u2.timestamp[flag]) for xx in u2.timestamp[flag:]]
        t = u1.timestamp[:k1]+tt
        if len(new)>3:
            us = user(i)
            us.set_user(i, new, beh, t)
            enhance_net.append(new)
            u2_list_net.append(us)
            i+=1

for x in enhance_net:
    print(len(x))

6
7
8
22
4
7
5
25
20
7
10
16
20
9
14
6
5
12
5
4
5
9
18
7
5
32
5
56
4
8


In [24]:
# 以上为随机拼接
new_res_net = []
def gen_new(u):
    length = u.get_seq_len()
    for i in range(length):
        tmp = [u.user, u.sequence[i], u.behavior[i], u.timestamp[i]]
        new_res_net.append(tmp)
for u_i in u2_list_net:
    gen_new(u_i)

new_res_net = np.array(new_res_net)

In [25]:
new_net = np.concatenate((net2, new_res_net), axis=0)
new_net

array([[1, 1, 'enter', 1413883798],
       [1, 1, 'done', 1413883869],
       [1, 1, 'watch', 1415244162],
       ...,
       ['276', '1', 'done', '1419388799'],
       ['276', '1', 'tag', '1422916025'],
       ['276', '1', 'watch', '1423787569']], dtype=object)

In [26]:
new_net2 = pd.DataFrame(new_net)
new_net2

0    1         2           3
0       1    1     enter  1413883798
1       1    1      done  1413883869
2       1    1     watch  1415244162
3       1    1       tag  1415330742
4       2    1     watch  1414155169
...   ...  ...       ...         ...
3952  276  285  duration  1415608075
3953  276    1       tag  1416534619
3954  276    1      done  1419388799
3955  276    1       tag  1422916025
3956  276    1     watch  1423787569

[3957 rows x 4 columns]

In [27]:
new_net2.to_csv('net_mb_KG_e1.txt', sep = '\t', index=False, header=None)

In [ ]:
#引入专家知识——固定知识点路径

为mooper完成数据增强

In [1]:
import pandas as pd
import numpy as np

data_sci = pd.read_csv('../data_sci_mb.txt',names=['user','item','behavior','time'], sep='\t')
computer = pd.read_csv('../computer_mb.txt',names=['user','item','behavior','time'], sep='\t')
c_class = pd.read_csv('../c_class_mb.txt',names=['user','item','behavior','time'], sep='\t')

In [2]:
class user:
    def __init__(self, user_id) -> None:
        self.sequence = []
        self.behavior = []
        self.timestamp = []
        self.user = user_id
    
    def get_seq_len(self):
        return len(self.sequence)

    def get_seq_part(self,i):
        self.length = self.get_seq_len()
        if i>self.length:
            return self.sequence
        else:
            return self.sequence[:i]

    def add_seq(self,data):
        self.sequence.append(data['item'])
        self.behavior.append(data['behavior'])
        self.timestamp.append(data['time'])

    def find(self,x):
        if x in self.sequence:
            t = self.sequence.index(x)
            return t+1
        else:
            return -1

    def set_user(self, user_id, seq, beh, t):
        self.user = user_id
        self.sequence = seq
        self.behavior = beh
        self.timestamp = t

In [21]:
data_sci[data_sci['user'].isin(data_sci.groupby('user').count()[data_sci.groupby('user').count()['item']>3].index)]

user  item   behavior        time
2         2   128     medium  1540214275
3         2   128       easy  1540214275
4         2   136     medium  1543805890
5         2   125       easy  1543806006
6         2   125     medium  1543806006
...     ...   ...        ...         ...
79902  8740   125       easy  1577588993
79903  8740   125  difficult  1577589503
79904  8740   127       easy  1577590584
79905  8740   127     medium  1577590709
79906  8740   135     medium  1577591957

[74893 rows x 4 columns]

In [ ]:
data_sci2 = data_sci[data_sci['user'].isin(data_sci.groupby('user').count()[data_sci.groupby('user').count()['item']>3].index)]

In [4]:
data_sci['user'].nunique()

8741

In [17]:
u_data_sci = []
for i in range(data_sci['user'].nunique()+1):
    tmp = user(i)
    if tmp.get_seq_len()>1:
        u_data_sci.append(tmp)

temp = 0
for index, row in data_sci.iterrows():
    u_data_sci[row['user']].add_seq(row)

0

In [15]:
len(u_data_sci)

1

In [6]:
print(len(u_data_sci))

8742


In [8]:
res_data_sci = []
for i in range(247):
    res_data_sci.append(u_data_sci[i].sequence)

In [9]:
length_data_sci = []
for s in res_data_sci:
    length_data_sci.append(len(s))
print(min(length_data_sci),np.average(length_data_sci),max(length_data_sci))

1 4.838056680161944 31


In [13]:
import random

enhance_data_sci = []
u2_list_data_sci = []
i=len(u_data_sci)+1
for _ in range(len(u_data_sci)//20):
    t1 = random.randint(1,len(u_data_sci))
    t2 = random.randint(1,len(u_data_sci))
    u1 = u_data_sci[t1]
    print(u1.user, u1.get_seq_len())
    u2 = u_data_sci[t2]
    u1_len = u1.get_seq_len()
    k1 = random.randint(1,u1_len-1)
    x = u1.sequence[k1]
    flag = u2.find(x)
    #print(flag)
    flag_time = u1.timestamp[k1]
    if flag>0:
        new = u1.sequence[:k1]+u2.sequence[flag:]
        beh = u1.behavior[:k1]+u2.behavior[flag:]
        tt = [xx + abs(flag_time - u2.timestamp[flag]) for xx in u2.timestamp[flag:]]
        t = u1.timestamp[:k1]+tt
        if len(new)>3:
            us = user(i)
            us.set_user(i, new, beh, t)
            enhance_net.append(new)
            u2_list_net.append(us)
            i+=1

4377 5
2873 1


ValueError: empty range for randrange() (1,1, 0)